FROM node:18-alpine

WORKDIR /usr/votting-app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]

//////

FROM node:16

WORKDIR /usr/app/client/
COPY client/package*.json ./
RUN yarn install 
COPY client/ ./
RUN npm build