version: "3"
services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3050:3050"
    container_name: server
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    # environment:
    #   - NODE_ENV=development
    #   - CHOKIDAR_USEPOLLING=true
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "8080:80"
      # - "3000:3000" if no nginx
    # command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    restart: on-failure
    container_name: client
